# Generated by Django 3.1.4 on 2021-01-02 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artikulli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikulli',
            name='kategoria',
            field=models.CharField(blank=True, choices=[('Politike', 'Politike'), ('Ekonomi', 'Ekonomi'), ('Opinion', 'Opinion'), ('Sporti', 'Sporti'), ('Kulture', 'Kulture')], max_length=10),
        ),
        migrations.AlterField(
            model_name='artikulli',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
