# Generated by Django 3.1.4 on 2020-12-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikulli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikulli',
            name='kategoria',
            field=models.CharField(blank=True, choices=[('Aktualitet', 'Aktualitet'), ('Politike', 'Politike'), ('Ekonomi', 'Ekonomi'), ('Opinion', 'Opinion'), ('Sporti', 'Sporti'), ('Kulture', 'Kulture')], max_length=10),
        ),
    ]
